/* Reciva Audio Mute */


#ifndef LINUX_RECIVA_DAC_MONITOR_H
#define LINUX_RECIVA_DAC_MONITOR_H

/* IOCTL Stuff */
#define RECIVA_DAC_MONITOR_IOCTL_BASE  'A'
#define IOC_DACM_REGISTER_CHECK     _IOR(RECIVA_DAC_MONITOR_IOCTL_BASE, 0, int)
#define IOC_DACM_ERROR_PIN_CHECK    _IOR(RECIVA_DAC_MONITOR_IOCTL_BASE, 1, int)


#endif
