/************************************************************
* This file was generated by cvs component font-generator
************************************************************/

/*********************************************
*             COPYRIGHT NOTICE               *
*                                            *
* All character font data in this program is *
* Copyright Roberts Radio Limited (c) 2006   *
*********************************************/

#define CLOCK_ICON_AM           0
#define CLOCK_ICON_PM           1
#define CLOCK_ICON_ALARM        2

// AM
0x007e,
0x00fe,
0x0190,
0x0310,
0x0190,
0x00fe,
0x007e,
0x0000,
0x03fe,
0x03fe,
0x0180,
0x00e0,
0x0180,
0x03fe,
0x03fe,

// PM
0x03fe,
0x03fe,
0x0210,
0x0210,
0x0230,
0x03e0,
0x01c0,
0x0000,
0x03fe,
0x03fe,
0x0180,
0x00e0,
0x0180,
0x03fe,
0x03fe,

// alarm
0x3ffe,
0x7c1f,
0x7007,
0x6003,
0x6003,
0x4001,
0x41c1,
0x5fc1,
0x41c1,
0x4081,
0x6083,
0x6083,
0x7007,
0x7c1f,
0x3ffe,
