{ /* MODE 0 - 2 lines, with icons on bottom row (used on ALTO) */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 15,
  .iHeight_c = 2,
  .iTopRowOffset_p = 8,
  .pfDrawIcon = draw_icon_16x16,
  .iIconPosition = 48,
  .iZoomMode = 8,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x6,
  .iIconLinePosition = -1,
},
{ /* MODE 1 - 4 lines, no icons */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 15,
  .iHeight_c = 4,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = NULL,
//.iIconPosition = 0,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x6,
  .iIconLinePosition = -1,
},
{ /* MODE 2 - 3 lines, with icons on bottom row */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 15,
  .iHeight_c = 3,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 56,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x6,
  .pfDrawSmallClock = draw_small_clock,
  .iIconLinePosition = -1,
},
{ /* MODE 3 - LCD_TM13264CBCG_MODE_CONFIG983 */
  .tFontSize = FONT_SIZE_11x8,
  .iWidth_c = 15,
  .iHeight_c = 3,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = NULL,
//.iIconPosition = 0,
  .iZoomMode = -1,
  .iInverseBleed = 1,
  .pfDrawClock = draw_clock_config2,
  .pfDrawArrow = draw_arrow_none,
  .iIconLinePosition = -1,
},
{ /* MODE 4 - AMAX - 95 * 17 pixels */
  /* LCD_TM13264CBCG_MODE_AMAX_KDC162A28BXXBB_95x17 */
  .tFontSize = FONT_SIZE_8x6,
  .iWidth_c = 14,
  .iHeight_c = 2,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = NULL,
//.iIconPosition = 0,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = NULL,
  .pfDrawArrow = draw_arrow_8x5,
  .iIconLinePosition = -1,
},    
{ /* MODE 5 -  LCD_TM13264CBCG_MODE_SSD0323_128x64 - should have zoom enabled? */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 15,
  .iHeight_c = 3,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 56,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_none,
  .iIconLinePosition = -1,
},
{ /* MODE 6 - 6 lines, with icons on bottom row */
  /* LCD_TM13264CBCG_MODE_CONFIG1009 */
  .tFontSize = FONT_SIZE_8x6,
  .iWidth_c = 20,
  .iHeight_c = 6,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 56,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config1,
  .pfDrawArrow = draw_arrow_8x5,
  .iIconLinePosition = -1,
},
{ /* MODE 7 - LCD_TM13264CBCG_MODE_CONFIG985 */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 15,
  .iHeight_c = 3,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 56,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x5,
  .pfDrawSmallClock = draw_small_clock,
  .iIconLinePosition = -1,
},
{ /* MODE 8 - zoom of mode 0 */
  .tFontSize = FONT_SIZE_32x16,
  .iWidth_c = 8,
  .iHeight_c = 2,
  .iTopRowOffset_p = 0,
  .iTopRowOffset_p = 8,
  .pfDrawIcon = NULL,
//.iIconPosition = 0,
  .iZoomMode = 0,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_none,
  .iIconLinePosition = -1,
},
{ /* MODE 9 - 4 lines, no icons, 14 chars wide */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 14,
  .iHeight_c = 4,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = NULL,
//.iIconPosition = 0,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x6,
  .iIconLinePosition = -1,
},
{ /* MODE 10 - 3 lines, icons in bottom row, 14 chars wide */
  .tFontSize = FONT_SIZE_16x8,
  .iWidth_c = 14,
  .iHeight_c = 3,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 56,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_16x6,
  .pfDrawSmallClock = draw_small_clock,
  .iNoSignalStrength = 1,
  .iIconLinePosition = -1,
},
{ /* MODE 11 - 4 lines, icons in bottom row */
  .tFontSize = FONT_SIZE_8x6,
  .iWidth_c = 22,
  .iHeight_c = 4,
  .iTopRowOffset_p = 0,
  .pfDrawIcon = draw_icon_8x8,
  .iIconPosition = 40,
  .iZoomMode = -1,
  .iInverseBleed = 0,
  .pfDrawClock = draw_clock_config0,
  .pfDrawArrow = draw_arrow_8x5,
  .iNoSignalStrength = 1,
  .iIconLinePosition = -1,
},
