#!/bin/sh
# Sharpfin project
# Copyright (C) by Steve Clarke <smclarke@trumpton.org.uk> and 
#   Ico Doornekamp <ico@zevv.nl>
# 2011-11-30 Philipp Schmidt
#   Added to github 
# 
# This file is part of the sharpfin project
#  
# This Library is free software: you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this source files. If not, see
# <http://www.gnu.org/licenses/>.

/bin/rm -f libreciva-src-*.tar.bz2 libreciva-src.tar
REV="`cat libreciva/README | grep '$Revision' | cut -d' ' -f2`"
(cd libreciva ; make clean )
find libreciva -name "*~" -exec /bin/rm -f {} \;
find libreciva -name "~*" -exec /bin/rm -f {} \;
tar cf libreciva-src-$REV.tar --exclude .svn LICENSE Rules.mak libreciva include
bzip2 libreciva-src-$REV.tar
